site_name: "rmarc"
site_url: "https://rmarc.readthedocs.io/"
site_author: "Matthew Martin <matthewdeanmartin@gmail.com>"
site_description: "A pymarc-compatible MARC21 record library with a Rust core for high performance."

repo_url: "https://github.com/matthewdeanmartin/rmarc"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - 'Home': 'index.md'
  - 'Change Log': '../CHANGELOG.md'
