name: Build Wheels

on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]


permissions:
  contents: read

jobs:
  build-wheels:
    name: Wheels / ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
          - name: linux-aarch64
            os: ubuntu-24.04-arm
          - name: windows-amd64
            os: windows-latest
          - name: macos-x86_64
            os: macos-15-intel
          - name: macos-arm64
            os: macos-14

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1

      - name: Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build wheels
        uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55 # v4.1.0

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-${{ matrix.name }}
          path: wheelhouse/*.whl
          if-no-files-found: error
          retention-days: 7
